# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: bionic
language: r
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
    osx_image: xcode11.3

cache: packages
language: R
cache: packages

script:
  - travis_wait 30 R CMD build .
  - travis_wait 100 R CMD check *tar.gz

after_failure:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat /home/travis/build/Giappo/jap/jap.Rcheck/00install.out; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat /home/travis/build/Giappo/jap/jap.Rcheck/tests/testthat.Rout.fail; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cat /Users/travis/build/Giappo/jap/jap.Rcheck/00install.out; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cat /Users/travis/build/Giappo/jap/jap.Rcheck/tests/testthat.Rout.fail; fi
